### PR TITLE
Update buildpack to use the latest version of Go

### PR DESCRIPTION
**Pull request by theothertomelliott**

### CODE REVIEW

**Comment by brendensoares** [comment]
What are the consequences of increasing this version? I'm not familiar enough with Heroku.

Thanks.

**Comment by jeevatkm** [comment]
My suggestion is not update it to latest version; instead update it to `1.4` for `v0.13.0` release. 

**Here is my explanation:**
`ver=go${GOVERSION:-1.3}` : `GOVERSION` is environment variable and `-1.3` is default value if doesn't find one

User can conveniently override by setting value in `GOVERSION`.  For example: 
```
$ export GOVERSION=1.6.2

# fire the commands
# OR

$ GOVERSION=1.6.2 <commands-goes-here>
```

By default script fallback to minimum required version for `v0.13.0` is Go `1.4`

**Comment by jeevatkm** [comment]
@theothertomelliott Thanks for your contribution to Revel. Please use `GOVERSION` environment variable to override Go version.

I'm closing this one also [I have updated the minimum version in Go 1.4](https://github.com/revel/heroku-buildpack-go-revel/commit/7dfc28c47ab12e7bb750f04935500a4ccae3b143).

**Comment by ghost** [comment]
It's good user can override the version. Though still it's not clear to me why use 1.4 instead of the latest supported one by default? Who wants to use 1.4 if there is support of 1.6.2 and what's their motivation behind that?

**Pull request closed without merging**
